function max_state_dur = MaxStateDur(obj) %#ok<INUSD>
    %TODO add in the spoke only states if needed
    max_state_dur = {...
        'state_0',                  120;...
        'check_next_trial_ready',   120;...
        'wait_for_cpoke',           Inf;...
        'settling_in',               30;...
        'cpoke',                     30;...
        'cout_wait_for_viol',        30;...
        'cin_wait_for_go',           30;...
        'cout_wait_for_go',          30;...
        'early_spoke_wait_for_go',   30;...
        'pre_give_delay',            30;...
        'give_state',                30;...
        'go_state',                  30;...
        'wait_for_spoke',            60;...
        'hit_state',                 30;...
        'drink_state',               60;...
        'temp_error_state',          60;...
        'wait_for_spoke_retry',      60;...
        'retry_hit_state',           60;...
        'error_state',              120;...
        'violation_state',           30;...
        'violation_penalty_state',  120;...
        'no_answer_state',          120;...
        'final_state',              120;
    };
    
    end